### ISSUE TITLE
FYI, this was posted to / quickly removed from HN

### ISSUE THREAD

**Issue by lattejed** [kelukelugames/Last-Words#1]
As an FYI, this made it to the front page of HN and was quickly removed. 

https://news.ycombinator.com/item?id=12071405

It hasn't been marked as flagged or dead but it no longer appears on the site, other than that direct link.

Also, one of the comments pointing out that a few of these bans seemed unjustified has disappeared completely. The poster may have removed it due to down votes. Not sure why -- the post was reasonable / within site guidelines.

=(

**Comment by kelukelugames** [comment]
Thanks for letting me know. I emailed the mods.

**Comment by kelukelugames** [comment]
Mod says users flagged it.

**Comment by lattejed** [comment]
I wasn't aware that made stories disappear as opposed to marking them as flagged. Anyway, however they want to run their site...

**Comment by kelukelugames** [comment]
Ditto. Again, thanks for reporting the issue. Here is the moderator response.

"Users flagged it, probably because of the meta aspect combined with the drama aspect—that's two kinds of HN fluffiness that we (and users) tend to frown on. As a moderator I must side with the flaggers in this case, but as a reader I have to admit that it was pretty funny! and a pretty clever use of the API.

Daniel"
